networks:
  kahf-net:
    external: true
volumes:
  kahf-redis:
    name: 'kahf-redis'
  kahf-mysql:
    name: 'kahf-mysql'

services:

  web:
    restart: "no"
    volumes:
      - ../codes/public:/var/www/html/public
    ports:
      - ${HTTP_PUBLISH_PORT}:80
    networks:
      kahf-net:
        aliases:
          - kahf-web

  app:
    env_file:
      - .envs/php-ini.env
    restart: "no"
    volumes:
      - ../codes:/var/www/html
    networks:
      kahf-net:
        aliases:
          - kahf-app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    container_name: redis-server
    env_file:
      - .envs/redis.env
    ports:
      - ${REDIS_PUBLISH_PORT}:6379
    networks:
      kahf-net:
        aliases:
          - kahf-redis
    volumes:
      - kahf-redis:/data

  mysql:
    env_file:
      - .envs/mysql.env
    ports:
      - ${MYSQL_PUBLISH_PORT}:3306
    volumes:
      - kahf-mysql:/var/lib/mysql
      - ./mysql/sqls:/sqls
    networks:
      kahf-net:
        aliases:
          - kahf-mysql

#  scheduler:
#    env_file:
#      - .envs/php-ini.env
#    volumes:
#      - ../codes:/var/www/html
#    networks:
#      kahf-net:
#        aliases:
#          - kahf-scheduler